// <auto-generated />
namespace WebAppAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migraion2017102900 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migraion2017102900));
        
        string IMigrationMetadata.Id
        {
            get { return "201710291347330_Migraion2017102900"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
